services:
  app:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ${ENV_FILE}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
