services:
  app:
    build: .
    ports:
      - "4321:4321"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
