services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ${ENV_FILE}
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
